title: Nico's Board
author: Nichole
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my pubnlic board for everyone to read my blog and access my public mood board on my instagram.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
minima: 
